name: Build Kernels at PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:

  Build:
    name: Compile
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'igorpecovnik' }}
    steps:
      - name: Build
        run: |

          echo "${{ github.event.pull_request.head.sha }}"
